sudo: required
services:
  - docker

before_install:
  - docker build -t inviewd/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true inviewd/docker-react npm run test -- --coverage
git status
deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-us-east-2-148286885012'
  bucket_path: 'docker-react'
  on:
    branch:master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
